import numpy as np
from typing import List, Optional, Any, Union, Tuple, Sequence
from numpy.typing import NDArray
from core.particles.particles import ParticleArray
from core.other.typing_definitions import Length, Activity, Energy, Time, Vector3D, Float

class Source:
    distribution: NDArray[np.float64]
    initial_activity: NDArray[np.float64]
    voxel_size: Length
    size: Vector3D
    radiation_type: str
    energy: np.ndarray
    half_life: Time
    timer: Time
    transformation_matrix: NDArray[np.float64]
    rng: np.random.Generator
    emission_table: List[NDArray[Any]]

    def __init__(self, distribution: Any, activity: Optional[Any] = None, voxel_size: Length = ..., radiation_type: str = 'Gamma', energy: Union[float, List[List[float]]] = ..., half_life: Time = ..., rng: Optional[np.random.Generator] = None, precision: Any = ...) -> None: ...
    def translate(self, x: float = 0., y: float = 0., z: float = 0., in_local: bool = False) -> None: ...
    def rotate(self, alpha: float = 0., beta: float = 0., gamma: float = 0., rotation_center: Sequence[float] = ..., in_local: bool = False) -> None: ...
    def convert_to_global_position(self, position: Vector3D) -> Vector3D: ...
    def _generate_emission_table(self) -> None: ...
    @property
    def activity(self) -> float: ...
    @property
    def nuclei_number(self) -> float: ...
    def set_state(self, timer: Optional[Time], rng_state: Optional[Any] = None) -> None: ...
    def generate_energy(self, n: int) -> NDArray[np.float64]: ...
    def generate_position(self, n: int) -> Vector3D: ...
    def generate_emission_time(self, n: int) -> Tuple[NDArray[np.float64], float]: ...
    def generate_direction(self, n: int) -> Vector3D: ...
    def generate_particles(self, n: int) -> ParticleArray: ...

class PointSource(Source):
    def __init__(self, activity: float, energy: float, size: Length = ..., half_life: Time = ..., rng: Optional[np.random.Generator] = None) -> None: ...

class Тс99m_MIBI(Source):
    def __init__(self, distribution: Any, activity: Optional[Any] = None, voxel_size: Length = ...) -> None: ...

class I123(Source):
    def __init__(self, distribution: Any, activity: Optional[Any] = None, voxel_size: Length = ...) -> None: ...

class SourcePhantom(Тс99m_MIBI):
    def __init__(self, phantom_name: str, activity: Optional[Any] = None, voxel_size: Length = ...) -> None: ...

class efg3(SourcePhantom):
    def __init__(self, activity: float) -> None: ...

class efg3cut(SourcePhantom):
    def __init__(self, activity: float) -> None: ...

class efg3cutDefect(SourcePhantom):
    def __init__(self, position: Any, activity: float, rotation_angles: Optional[Any] = None, rotation_center: Optional[Any] = None) -> None: ...
