[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
exclude = (phantoms|presets|output data|tables|logs)

[mypy-vtkmodules.*]
ignore_missing_imports = True

[mypy-numba.*]
ignore_missing_imports = True

[mypy-cffi.*]
ignore_missing_imports = True

[mypy-hepunits.*]
ignore_missing_imports = True

[mypy-telebot.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True
