[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "NMSimToolkit"
version = "0.1.0"
description = "Nuclear Medicine Simulation Toolkit"
authors = [
  { name="Mikhail Gurko" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cffi",
    "h5py",
    "hepunits",
    "llvmlite",
    "numba",
    "numpy",
    "pycparser",
    "scipy",
    "pint",
    "pydantic",
    "pyyaml"
]

[project.optional-dependencies]
test = [
    "pytest",
    "psutil"
]
