import numpy as np
from typing import List, Optional, Any, Tuple, Union, Generic
from core.particles.particles import ParticleArray
from core.geometry.volumes import ElementaryVolume
from core.physics.processes import Process
from core.other.typing_definitions import Precision

class PropagationWithInteraction(Generic[Precision]):
    processes: List[Process[Precision]]
    rng: np.random.Generator
    attenuation_database: Any
    def __init__(self, processes_list: Optional[List[type]] = None, attenuation_database: Optional[Any] = None, rng: Optional[np.random.Generator] = None) -> None: ...
    def __call__(self, particles: ParticleArray[Precision], volume: ElementaryVolume[Precision]) -> Optional[np.recarray]: ...
    def get_processes_LAC(self, particles: ParticleArray[Precision], materials: Any) -> np.ndarray: ...
    def get_total_LAC(self, particles: ParticleArray[Precision], materials: Any) -> np.ndarray: ...
    def generate_free_path(self, particles: ParticleArray[Precision], materials: Any) -> np.ndarray: ...
    def choose_process(self, processes_LAC: np.ndarray, total_LAC: np.ndarray) -> List[Tuple[Process[Precision], np.ndarray]]: ...
