import numpy as np
from dataclasses import dataclass
from typing import Dict, List, Any, Tuple, Optional
from numpy.typing import NDArray
from core.other.nonunique_array import NonuniqueArray

class Composition(Tuple[float, ...]):
    def _asdict(self) -> Dict[str, float]: ...

@dataclass(eq=True, frozen=True)
class Material:
    name: str
    type: str
    density: float
    composition: Any
    ZtoA_ratio: float
    ID: int
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    @property
    def Zeff(self) -> float: ...
    @property
    def composition_dict(self) -> Dict[str, float]: ...
    @property
    def composition_array(self) -> NDArray[np.float64]: ...

class MaterialArray(NonuniqueArray):
    def __new__(cls, shape: Tuple[int, ...]) -> 'MaterialArray': ...
    @property
    def material_list(self) -> List[Material]: ...
    @property
    def Zeff(self) -> NDArray[np.float64]: ...
    @property
    def density(self) -> NDArray[np.float64]: ...
