import numpy as np
from dataclasses import dataclass
from typing import Dict, List, Any, Tuple, Optional
from numpy.typing import NDArray
from core.other.nonunique_array import NonuniqueArray
from core.other.typing_definitions import Float

class Composition(Tuple[Float, ...]):
    def _asdict(self) -> Dict[str, Float]: ...

@dataclass(eq=True, frozen=True)
class Material:
    name: str = ...
    type: str = ...
    density: Float = ...
    composition: Any = ...
    ZtoA_ratio: Float = ...
    ID: int = ...
    def __lt__(self, other: Any) -> bool: ...
    def __le__(self, other: Any) -> bool: ...
    def __gt__(self, other: Any) -> bool: ...
    def __ge__(self, other: Any) -> bool: ...
    @property
    def Zeff(self) -> Float: ...
    @property
    def composition_dict(self) -> Dict[str, Float]: ...
    @property
    def composition_array(self) -> NDArray[Float]: ...

class MaterialArray(NonuniqueArray):
    def __new__(cls, shape: Tuple[int, ...]) -> 'MaterialArray': ...
    @property
    def material_list(self) -> List[Material]: ...
    @property
    def Zeff(self) -> NDArray[Float]: ...
    @property
    def density(self) -> NDArray[Float]: ...
