import numpy as np
from datetime import timedelta
from typing import Any, Tuple, List, Optional

def compute_translation_matrix(translation: Any) -> np.ndarray: ...
def compute_rotation_matrix(angles: Any) -> np.ndarray: ...
def unique_with_indices(array: Any) -> List[Tuple[Any, np.ndarray]]: ...
def datetime_from_seconds(seconds: float) -> timedelta: ...
def make3DRGBA(array3D: np.ndarray, lut: Optional[Any] = None, levels: Optional[Any] = None) -> np.ndarray: ...
