import numpy as np
from datetime import timedelta
from typing import Any, List, Optional, Sequence, Tuple, Union
from numpy.typing import NDArray
from core.other.typing_definitions import Float

def compute_translation_matrix(translation: Union[NDArray[Float], Sequence[Float]]) -> NDArray[Float]: ...
def compute_rotation_matrix(angles: Union[NDArray[Float], Sequence[Float]]) -> NDArray[Float]: ...
def unique_with_indices(array: Sequence[Any]) -> List[Tuple[Any, NDArray[np.int64]]]: ...
def datetime_from_seconds(seconds: Float) -> timedelta: ...
