import numpy as np
from typing import Optional, Tuple, Any
from core.geometry.volumes import Volume
from core.other.typing_definitions import Length

class VolumeTester:
    volume: Volume
    def __init__(self, volume: Volume) -> None: ...
    def getDistribution(self, materialParameter: str = 'density', voxelSize: Length = ...) -> Tuple[np.ndarray, list]: ...

class VolumeVisualization:
    data: Optional[np.ndarray]
    voxelSize: Length
    def __init__(self, data: Optional[np.ndarray] = None, voxelSize: Length = ..., sliceDensity: int = 1, smooth: bool = False, glOptions: str = 'translucent') -> None: ...
    def _gradientChanged(self) -> None: ...
    def setData(self, data: np.ndarray, voxelSize: Optional[Length] = None) -> None: ...
    def show(self) -> None: ...
    def exec(self) -> None: ...

class VolumeDensityVisualization(VolumeVisualization):
    volume: Volume
    volumeTester: VolumeTester
    def __init__(self, volume: Volume, voxelSize: Length = ...) -> None: ...
    def show(self) -> None: ...
