import numpy as np
from abc import ABC, abstractmethod
from typing import Union, Sequence, Tuple, Any
from numpy.typing import NDArray
from core.other.typing_definitions import Length, Vector3D, Precision

class Geometry(ABC):
    size: Vector3D
    def __init__(self, size: Union[Sequence[Length], Vector3D]) -> None: ...
    @property
    def half_size(self) -> Vector3D: ...
    @property
    def quarter_size(self) -> Vector3D: ...
    @abstractmethod
    def check_outside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    @abstractmethod
    def check_inside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    @abstractmethod
    def cast_path(self, position: Vector3D, direction: Vector3D) -> Tuple[NDArray[Precision], Union[bool, NDArray[np.bool_]]]: ...

class Box(Geometry):
    distance_method: str
    distance_epsilon: Length
    def __init__(self, x: Length, y: Length, z: Length, **kwds: Any) -> None: ...
    def check_outside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    def check_inside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    def cast_path(self, position: Vector3D, direction: Vector3D) -> Tuple[NDArray[Precision], Union[bool, NDArray[np.bool_]]]: ...
    def ray_marching(self, position: Vector3D, *args: Any) -> Tuple[NDArray[Precision], Union[bool, NDArray[np.bool_]]]: ...
    def ray_casting(self, position: Vector3D, direction: Vector3D) -> Tuple[NDArray[Precision], Union[bool, NDArray[np.bool_]]]: ...
