import numpy as np
from typing import List, Any, Optional, Tuple, Union, Type, TypeVar, Sequence
from numpy.typing import NDArray
from core.geometry.geometries import Geometry
from core.materials.materials import Material, MaterialArray
from core.other.nonunique_array import NonuniqueArray
from core.geometry.flattened_scene import FlattenedScene
from core.scene.nodes import CompositeNode, SpatialNode
from core.other.typing_definitions import Vector3D, Length, Float, CMaterialFunc

T = TypeVar('T')

class Volume(CompositeNode):
    geometry: Geometry
    material: Material
    name: str
    def __init__(self, geometry: Geometry, material: Material, name: Optional[str] = None) -> None: ...
    @property
    def flattened_scene(self) -> FlattenedScene: ...
    @property
    def material_cfunc(self) -> CMaterialFunc: ...
    @property
    def majorant_material(self) -> Material: ...
    @property
    def material_list(self) -> List[Material]: ...
    @property
    def size(self) -> Vector3D: ...
    @size.setter
    def size(self, value: Vector3D) -> None: ...
    @property
    def geometry_buffer(self) -> NDArray[np.void]: ...
    @property
    def top_volume(self) -> 'Volume': ...
    def invalidate_scene(self) -> None: ...
    def dublicate(self) -> 'Volume': ...
    def set_parent(self, parent: 'CompositeNode') -> None: ...

class VolumeArray(NonuniqueArray):
    element_list: List[Optional[Volume]]
    @property
    def material(self) -> MaterialArray: ...
    def type_matching(self, type: Type[T]) -> NDArray[np.bool_]: ...
