import numpy as np
from typing import List, Any, Optional, Tuple, Union, Type, TypeVar, Sequence
from numpy.typing import NDArray
from core.geometry.geometries import Geometry
from core.materials.materials import Material, MaterialArray
from core.other.nonunique_array import NonuniqueArray
from core.geometry.flattened_scene import FlattenedScene
from core.other.typing_definitions import Vector3D, Length, Float, CFuncAddress

T = TypeVar('T')

class Volume:
    geometry: Geometry
    material: Material
    name: str
    def __init__(self, geometry: Geometry, material: Material, name: Optional[str] = None) -> None: ...
    @property
    def flattened_scene(self) -> FlattenedScene: ...
    @property
    def material_cfunc_address(self) -> CFuncAddress: ...
    @property
    def majorant_material(self) -> Material: ...
    @property
    def material_list(self) -> List[Material]: ...
    @property
    def size(self) -> Vector3D: ...
    @size.setter
    def size(self, value: Vector3D) -> None: ...
    @property
    def geometry_buffer(self) -> NDArray[np.void]: ...
    def invalidate_scene(self) -> None: ...
    def dublicate(self) -> 'Volume': ...
    def check_inside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    def check_outside(self, position: Vector3D) -> Union[bool, NDArray[np.bool_]]: ...
    def cast_path(self, position: Vector3D, direction: Vector3D) -> Tuple[NDArray[Float], 'VolumeArray']: ...
    def get_material_by_position(self, position: Vector3D) -> MaterialArray: ...

class VolumeWithChilds(Volume):
    childs: List['TransformableVolume']
    def __init__(self, geometry: Geometry, material: Material, name: Optional[str] = None) -> None: ...
    def invalidate_geometry_buffer(self) -> None: ...
    def add_child(self, child: 'TransformableVolume') -> None: ...

class TransformableVolume(Volume):
    transformation_matrix: NDArray[Float]
    parent: Optional[VolumeWithChilds]
    def __init__(self, geometry: Geometry, material: Material, name: Optional[str] = None) -> None: ...
    @property
    def total_transformation_matrix(self) -> NDArray[Float]: ...
    def convert_to_local_position(self, position: Vector3D, as_parent: bool = True) -> Vector3D: ...
    def convert_to_local_direction(self, direction: Vector3D, as_parent: bool = True) -> Vector3D: ...
    def translate(self, x: Float = ..., y: Float = ..., z: Float = ..., inLocal: bool = False) -> None: ...
    def rotate(self, alpha: Float = ..., beta: Float = ..., gamma: Float = ..., rotation_center: Sequence[Float] = ..., inLocal: bool = False) -> None: ...
    def invalidate_geometry_buffer(self) -> None: ...
    def set_parent(self, parent: VolumeWithChilds) -> None: ...

class TransformableVolumeWithChild(TransformableVolume, VolumeWithChilds): ...

class VolumeArray(NonuniqueArray):
    element_list: List[Optional[Volume]]
    @property
    def material(self) -> MaterialArray: ...
    def type_matching(self, type: Type[T]) -> NDArray[np.bool_]: ...
