import numpy as np
from typing import Optional, Tuple, Any
from core.geometry.woodcoock_volumes import WoodcockParameticVolume
from core.materials.materials import Material, MaterialArray
from core.other.typing_definitions import Length, Vector3D, Float

class WoodcockVoxelVolume(WoodcockParameticVolume):
    material_distribution: MaterialArray
    _voxel_size_ratio: Length
    def __init__(self, voxel_size: Length, material_distribution: MaterialArray, name: Optional[str] = None) -> None: ...
    @property
    def voxel_size(self) -> Vector3D: ...
    @voxel_size.setter
    def voxel_size(self, value: Vector3D) -> None: ...
    @property
    def material(self) -> Material: ...
    @material.setter
    def material(self, value: Material) -> None: ...
    def _parametric_function(self, position: Vector3D) -> Tuple[np.ndarray, Any]: ...
