import numpy as np
from typing import Tuple, Any, Union
from numpy.typing import NDArray
from core.geometry.volumes import TransformableVolume
from core.materials.materials import MaterialArray, Material
from core.other.typing_definitions import Vector3D, Float, CFuncAddress
from typing import List

class WoodcockVolume(TransformableVolume): ...

class WoodcockParameticVolume(WoodcockVolume):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def material_cfunc_address(self) -> CFuncAddress: ...
    def _compile_cfunc(self) -> Any: ...
    @property
    def material_list(self) -> List[Material]: ...
    def _parametric_function(self, position: Vector3D) -> Tuple[Union[NDArray[np.bool_], list], Any]: ...
    def get_material_by_position(self, position: Vector3D, local: bool = False, as_parent: bool = True) -> MaterialArray: ...
